# Generated by Django 4.1.1 on 2022-09-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_6',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_7',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_periods', to='timetable.lecture'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_no',
            field=models.IntegerField(null=True),
        ),
    ]
