# Generated by Django 4.1.1 on 2022-09-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timetable_period_1_remove_timetable_period_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Lecture',
            new_name='lecture',
        ),
    ]
